# Generated by Django 5.1.4 on 2024-12-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_match_opponent_name_match_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchaction',
            name='grid_cols',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='matchaction',
            name='grid_rows',
            field=models.IntegerField(default=16),
        ),
    ]
