FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /accounts

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev && \
    apt-get clean

COPY requirements.txt /accounts/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /accounts/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
